go_import_path: ManticoreDB
language: go
go: 1.13.6
notifications:
  email: false
branches:
  only:
    - master
    - beta
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)